name: startedpack
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cached_network_image: ^2.5.1
  camera_camera: ^1.0.34+1
  carousel_slider: ^3.0.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.0.0
  dio: ^3.0.10
  dotted_line: ^3.0.0
  firebase_analytics: ^7.0.1
  firebase_core: ^0.7.0
  firebase_messaging: 8.0.0-dev.15
  flutter_html: ^1.2.0
  flutter_map: ^0.12.0
  flutter_polyline_points: ^0.2.4
  flutter_svg: ^0.19.3
  fluttertoast: ^8.0.6
  geocoding: ^1.0.5
  geocoding_platform_interface: ^1.0.1+1
  geolocator: ^6.2.1
  get: ^3.25.6
  google_fonts: ^1.1.2
  google_maps_flutter: ^1.0.6
  google_maps_place_picker: ^1.0.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  im_stepper: ^0.1.3
  image_gallery_saver: ^1.6.9
  image_picker: ^0.6.7+22
  keyboard_actions: ^3.4.0
  loading: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  numberpicker: ^2.1.1
  package_info: ^2.0.0
  path_provider: ^1.6.28
  pattern_formatter: ^2.0.0
  permission_handler: ^5.0.1+2
  pinch_zoom: ^0.1.0
  pull_to_refresh: ^1.6.5
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  rflutter_alert: ^2.0.2
  screenshot: ^0.3.0
  share: ^2.0.1
  signature: ^3.2.1
  timelines: ^0.1.0
  url_launcher: ^5.7.10
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.2
  import_sorter: ^4.4.1
  lint: ^1.5.3
  logger: ^1.0.0
  pretty_dio_logger: ^1.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
